# See https://wiki.hypr.land/Configuring/Keywords/
$browser = firefox
$terminal = kitty
$fileManager = thunar
$menu = ~/.config/rofi/appmenu/appmenu.sh
$powerMenu = ~/.config/scripts/powermenu/powermenu.sh
