[mgr]
ratio = [1, 3, 4]
show_hidden = true
sort_dir_first = true
sort_by = "alphabetical"

[opener]
# Édition de texte avec Neovim
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" },
]
# Visualisation d'images avec nsxiv
view_img = [
    { run = 'nsxiv -a "$@"', detach = true, desc = "nsxiv" },
]

[open]
rules = [
    # Images : on utilise nsxiv
    { mime = "image/*", use = "view_img" },
    
    # Fichiers texte : on utilise nvim
    { mime = "text/*", use = "edit" },
    
    # Cas particulier : Fichiers JSON, scripts, etc. (souvent pas "text/*")
    { mime = "application/javascript", use = "edit" },
    { mime = "application/json", use = "edit" },
    
    # Catch-all pour tout ce qui est éditable (fallback)
    { name = "*.{txt,md,c,cpp,py,sh,lua,toml,conf,css}", use = "edit" },
]
